oss:
  ali:
    access-key: xxx
    access-secret: xxx
    access-domain: xxx
    end-point: https://oss-cn-shenzhen.aliyuncs.com
    bucket-name: xxx
    time-out: 300000

server:
  port: 8080
  undertow:
    io-threads: 8

spring:
  profiles:
    active: dev

  redis:
    database: 0
    port: 26379
    host: 127.0.0.1
    password: aTMr4wyZ%@a77VLb
    # 连接超时时长（毫秒）
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0

  resources:
    static-locations: classpath:/static/, classpath:META-INF/resources,  classpath:/resources

  mvc:
    throw-exception-if-no-handler-found: true